### PR TITLE
replaced req.body with req to use all request params in the middleware

### PR DESCRIPTION
**Pull request by thinkingmik**
I need to access to the request object when I call this:
```
server.exchange(oauth2orize.exchange.password(function(client, username, password, scope, req, callback) { 
...
// TODO: do something with req header object (not only body)
...
```

I think that it's a good idea passing the entire request object to the controller and not only the req.body.

### CODE REVIEW

**Comment by jaredhanson** [comment]
Could you provide details on the use case you have which requires a header?

**Comment by thinkingmik** [comment]
Beacause I need to save the caller's IP address into DB (not only the token) when it exchanges its credentials with a token. 
Another use case is that I want to create a jwt token (in the exchanges methods) with IP address and user agenti infos stored into payload.

**Comment by jaredhanson** [comment]
Instead of just changing the arity to pass `req` instead of `req.body`, could you add another arity, something like:

```
 if (arity == 6) {
    issue(client, code, redirectURI, req.body, req.headers, issued);
}
```

As is, the pull request breaks API compatibility for any applications that depend on the body being passed as the 4th argument.  The functionality is useful, and I'll merge it in if we can support it in a way that doesn't break compatibility.

**Comment by thinkingmik** [comment]
Yes, I agree with you that the best solution is to add another arity for backward compatibility. As soon as possible I change the pull request.
Thank you.

**Pull request closed without merging**
