### PR TITLE
fix docblocks

### PR DESCRIPTION
**Pull request by emmanuelgautier**
_parse, _response and _exchange server methods' visibility are public

### CODE REVIEW

**Comment by tellnes** [comment]
Those methods are not intended to be public. Why do you want to change that?

**Comment by emmanuelgautier** [comment]
Of course, but those methods can be called publicly so, for clarity reasons, it seem be better to indicate this in docblock.

**Comment by tellnes** [comment]
The point of declaring those as private in the comment code block is to say to those people reading the code that the should not use those methods.

The comment is not there to repeat the code, but to give extra information.

**Comment by jaredhanson** [comment]
No.  The _ prefix indicates that they are private.  This is just a convention, JavaScript obviously doesn't enforce this.  They are marked private, because from an API standpoint they are.  You should not be calling these from outside code, and if you are there is no guarantee that your code will continue to work in the future.

**Pull request closed without merging**
