### PR TITLE
updated examples to use secure id generation #142

### PR DESCRIPTION
**Pull request by mreinstein**

### CODE REVIEW

**Comment by FrankHassanabad** [comment]
What's weird is that strong loop's fork of oauth2orize also uses `uid2` as you are in your examples.  What's weird about that is that uid2 is using an undocumented node function of [pseudoRandomBytes](https://github.com/coreh/uid2/blob/master/index.js) 

which is still secure from my understanding of googling around but since it's not a documented function it could change to be just pseudo random or it could be remove all together.

I would just directly call the sync version that's documented:

`const buf = crypto.randomBytes(256);`

And I would do it within the utils package since it is a nice abstraction already.  Then you only have 1 or two lines of code changed and the examples stay pretty much the same.

**Comment by mreinstein** [comment]
> I would just directly call the sync version that's documented

I agree that it would be better to not use undocumented/unstable functions, but the library itself is already using `uid2` internally. `pseudoRandomBytes` is actually from openSSL which gets bundled with node by default.

I think the better solution would be to update to uid2 and update this project's deps to match.

**Comment by mreinstein** [comment]
I've submitted a PR for uid2 here: https://github.com/coreh/uid2/pull/15

**Comment by FrankHassanabad** [comment]
That library already has an open pull request to replace it from 29 days ago as a FYI:
https://github.com/coreh/uid2/pull/14

So your PR is a duplicate for uid2.

**Comment by mreinstein** [comment]
Also sent a PR to uid, hopefully one or both of them will publish a new version  https://github.com/matthewmueller/uid/pull/8

**Pull request closed without merging**
