### PR TITLE
Added custom token error description

### PR DESCRIPTION
**Pull request by onury**
Custom error description to be used when accessToken is not set. Fixes [issue #120](https://github.com/jaredhanson/oauth2orize/issues/120)

### CODE REVIEW

**Comment by tellnes** [comment]
You don't need this to get custom `error_description`. Just create a custom instance of `TokenError` in your callback.

Eg:

```js
var TokenError = require('oauth2orize').TokenError

// ...

function issue(client, username, passwd, scope, issued) {
  if (not_ok)
    return issued(new TokenError('custom error_description', 'invalid_grant'))
}
```


If this is going to be changed, I propose checking if the error argument is a string and if that is the case, use that as `error_description`.

Eg.

```js
function issued(err, accessToken, refreshToken, params) {
  if (err) {
    if (typeof err === 'string') { return next(new TokenError(err, 'invalid_grant')); }
    return next(err);
  }
  if (!accessToken) { return next(new TokenError('Invalid resource owner credentials', 'invalid_grant')); }
```

**Comment by onury** [comment]
@tellnes 
I'd prefer to simply set the `error_description` with just a parameter, instead of re-writing callbacks, etc..

About your second argument; 
`err` can be any error — unrelated to token. Your way, if any `string` is thrown previously, you'll treat it as token error. It should be passed to the next middleware as is. e.g. `next(err)`. I think, a separate parameter should be used here. That's why I named it `tokenErrDescription`.

**Comment by jaredhanson** [comment]
@telnes is correct in his first example. You can customize/i18n the error messages by invoking the callback with an error and the message you want.  I don't personally like having multiple ways to do something, when one good way already exists.

As far as the second proposal, I don't like that either.

I think the functionality desired in this pull requests already exists, so there's no reason to merge.

**Comment by tellnes** [comment]
I don't like the proposal with type checking either, I just think it is better than adding a new parameter.

+1 to just have one way of doing tings.

**Pull request closed without merging**
